---
framework: jest
postMerge:
  pattern:
    - './tests/**/*.test.js'
preMerge:
  pattern:
    - './tests/**/*.test.js'
preRun:
  command:
    - npm install
    - npm run prepublishOnly
postRun:
  command:
    - node --version
version: 2.1
